# Path to your oh-my-zsh installation.
export ZSH=~/.oh-my-zsh
export DISABLE_AUTO_TITLE='true'

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="snow"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"


# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
    archlinux
    aws
    colored-man-pages
    fzf-marks
    git
    vi-mode
    zsh-autosuggestions
    zsh-syntax-highlighting
)

# User configuration
source $ZSH/oh-my-zsh.sh
# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"
export PATH=$PATH:$HOME/go/bin:$HOME/.local/bin

# My aliases
alias v="nvim"
alias vimdiff="nvim -d"
alias r="ranger"
alias poweroff="systemctl poweroff"
alias reboot="systemctl reboot"
alias weather="curl wttr.in"

#vagrant aliases
alias vu="vagrant up"
alias vd="vagrant destroy"
alias vr="vagrant reload"
alias vh="vagrant halt"
alias vssh="vagrant ssh"

#Mac Aliases
if [ "$(uname)" = "Darwin" ]; then
    alias tar="gtar"
    alias grep="ggrep"
fi

# My functions
mvcd() {mv "$1" "$2" && cd "$2"; }
cpcd() {cp -r "$1" "$2" && cd "$2"; }

# Source other files
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

#Keybindings
bindkey '^g' fzm
