- name: make sure fish is installed
  community.general.homebrew:
    name: fish
    state: present

- name: set fish as default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /opt/homebrew/bin/fish
  become: yes
