- name: make sure fish is installed
  package:
    name: fish
    state: present
  become: yes

- name: set fish as default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/fish
  become: yes

- name: Include version vars
  include_vars: "{{ playbook_dir }}/versions.yaml"

- name: create bin directory if not exists
  file:
    path: "{{ playbook_dir }}/bin"
    state: directory

- name: Download kubectl
  shell:
    cmd: "curl -L -o bin/kubectl https://dl.k8s.io/release/v{{ kubectl }}/bin/linux/amd64/kubectl"

- name: Install kubectl
  shell:
    cmd: install -o root -g root -m 0755 bin/kubectl /usr/local/bin/kubectl
  become: yes
