#!/bin/sh
help() {
    echo "Usage: ./install [-p arg] [-w arg] [-d arg] [-g arg]"
    echo "-p (the password for the private mail account)"
    echo "-w (the password for the work mail account)"
    echo "-d (the password for the cal- and carddav account)"
    echo "-g (the password for the github account)"
    echo "-h (print this message)"
}

while getopts ':p:w:d:g:h' opt; do
    case $opt in
        p)
            private_pw=$OPTARG
            ;;
        w)
            work_pw=$OPTARG
            ;;
        d)
            dav_pw=$OPTARG
            ;;
        g)
            github_pw=$OPTARG
            ;;
        h)
            help
            ;;
        ?)
            echo "Invalid Parameter given. $(help)"
            ;;
    esac
done

DAV_PW=$dav_pw \
MAIL_PRIVATE_PW=$private_pw \
MAIL_WORK_PW=$work_pw \
GITHUB_PW=$github_pw \
ansible-playbook -i hosts main.yml --ask-become-pass
