- name: Setup local environment
  hosts: localhost
  vars:
    cert_path: /etc/ssl/certs/ca-certificates.crt
  roles:
    - base
    # - locale
    - git
    #   #- gnupg
    # - dmenu
    # - dunst
    - bspwm
    - fish
    - rust
    - go
    - alacritty
    # - ctags
    - syncthing
    # - nvim
    - helix
    - emacs
    # - ranger
    # - offlineimap
    # - qutebrowser
    # - mu
    - work
