- name: Setup local environment
  hosts: localhost
  vars:
    cert_path: /opt/homebrew/etc/openssl@1.1/cert.pem
  roles:
    - base
    - yabai
    - alacritty
    - ctags
    - git
    - fish
    - syncthing
    - nvim
    - emacs
    - offlineimap
    - mu
    - qutebrowser
