- name: install qutebrowser on Arch Linux
  become: yes
  package:
    name: qutebrowser
    state: present
    
- name: symlink qutebrowser dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/qutebrowser/files/{{ item }}"
    path: "~/.config/qutebrowser/{{ item }}"
    state: link
    force: yes
  loop:
    - config.py
    - quickmarks
