- name: make sure yabai is installed
  community.general.homebrew:
    name:
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd
    state: present

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/yabai/files/{{ item }}"
    path: ~/.{{ item }}
    state: link
    follow: false
    force: yes
  loop:
    - yabairc
    - skhdrc

- name: Start skhd Service
  command: brew services start skhd

#- name: Start yabi Service
#  command: brew services yabai
