- name: make sure bspwm is installed
  become: yes
  package:
    name:
      - bspwm
      - sxhkd
    state: present

- name: make sure polybar is installed on Ubuntu
  become: yes
  package:
    name:
      - polybar
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: download polybar on Arch
  git:
    repo: https://aur.archlinux.org/polybar.git
    dest: ~/workspace/polybar
  when: ansible_facts['os_family'] == "Archlinux"

- name: check if polybar was downloaded on Arch
  stat:
    path: ~/workspace/polybar
  register: polybar
  when: ansible_facts['os_family'] == "Archlinux"

- name: install polybar on Arch
  command: makepkg -si --noconfirm
  args:
    chdir: ~/workspace/polybar
  when: (ansible_facts['os_family'] == "Archlinux") and polybar.stat.exists

- name: make sure bspwm config directory is present
  file:
    path: ~/.config/bspwm
    state: directory

- name: symlink dotfile
  file:
    src: "{{ ansible_env.PWD }}/roles/bspwm/files/bspwmrc"
    path: ~/.config/bspwm/bspwmrc
    state: link
    follow: false
    force: yes

- name: symlink bar script
  file:
    src: "{{ ansible_env.PWD }}/roles/bspwm/files/bar"
    path: ~/.local/bin/bar
    state: link
    follow: false
    force: yes

- name: make sure polybar config directory is present
  file:
    path: ~/.config/polybar
    state: directory

- name: symlink polybar config
  file:
    src: "{{ ansible_env.PWD }}/roles/bspwm/files/config"
    path: ~/.config/polybar/config
    state: link
    follow: false
    force: yes

- name: symlink arch update count script
  file:
    src: "{{ ansible_env.PWD }}/roles/bspwm/files/arch-updates.sh"
    path: ~/.local/bin/arch-updates.sh
    state: link
    follow: false
    force: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: make sure shxkd config directory is present
  file:
    path: ~/.config/sxhkd
    state: directory

- name: symlink shxkdrc
  file:
    src: "{{ ansible_env.PWD }}/roles/bspwm/files/sxhkdrc"
    path: ~/.config/sxhkd/sxhkdrc
    state: link
    follow: false
    force: yes


