#!/bin/sh

#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)
#
exec dwm &
dwmstatus 2>&1 >/dev/null &
setxkbmap de nodeadkeys -option caps:escape &
feh --bg-scale ~/Seafile/My\ Library/wallpaper/hollowknight.png &
xclip &
dunst
