#! /bin/sh

sxhkd &

if xrandr -q | grep 'HDMI1 connected' && xrandr -q | grep 'DP2 connected'; then
    ~/.local/bin/fix_res.sh
    bspc monitor eDP1 -d 1
    bspc monitor HDMI1 -d 2 3 4 5 6 7 8 9
    bspc monitor DP2 -d 0
elif xrandr -q | grep 'HDMI1 connected'; then
    xrandr --output eDP1 --mode 1920x1080 --output HDMI1 --primary --mode 1920x1080 --right-of eDP1
    bspc monitor eDP1 -d 1
    bspc monitor HDMI1 -d 2 3 4 5 6 7 8 9 0
else
    bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
fi

########################## Border Settings ####################################
bspc config focused_border_color        "#3182bd"
bspc config border_width                1
bspc config window_gap                  0

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config remove_disabled_monitors    true
bspc config remove_unplugged_monitors   true

bspc rule -a Screenkey manage=off
# bspc rule -a polybar sticky=on
bspc rule -a Emacs state=tiled
bspc rule -a libreoffice state=tiled

############################ Autostart ########################################
~/.local/bin/bar
