- name: install git on Mac OSX
  community.general.homebrew:
    name: git
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: install git on Linux
  become: yes
  package:
    name: git
    state: present
  when: ansible_facts['os_family'] == "ArchLinux"

- name: symlink gitconfig
  file:
    src: "{{ ansible_env.PWD }}/roles/git/files/gitconfig"
    path: ~/.gitconfig
    state: link
    force: yes

- name: symlink global gitignore
  file:
    src: "{{ ansible_env.PWD }}/roles/git/files/gitignore_global"
    path: ~/.gitignore_global
    state: link
    force: yes
