- name: symlink neomutt files
  file:
    src: "{{ ansible_env.PWD }}/roles/mail/files/{{ item }}"
    path: "~/.config/mutt/{{ item }}"
    state: link
    force: yes
  loop:
    - account.privat
    - colors.rc
    - neomuttrc
    - vim-keys.rc

- name: symlink notmuch-config
  file:
    src: "{{ ansible_env.PWD }}/roles/mail/files/notmuch-config"
    path: ~/.notmuch-config
    state: link
    force: yes

- name: clone mailboxes-splitter
  git:
    repo: https://github.com/snowiow/mailboxes-splitter
    dest: ~/workspace/mailboxes-splitter
    accept_hostkey: yes

- name: install mailboxes-splitter
  command: stack install
  args:
    chdir: ~/workspace/mailboxes-splitter
