- name: symlink offlineimap.py
  file:
    src: "{{ ansible_env.PWD }}/roles/offlineimap/files/offlineimap.py"
    path: ~/.offlineimap.py
    state: link
    force: yes

- name: create offlineimaprc
  template:
    src: offlineimaprc.j2
    dest: "~/.offlineimaprc"
    follow: false
    force: yes
