- name: make sure packages are installed
  community.general.homebrew:
    name:
      - coreutils
      - fzf
      - gnu-sed
      - ledger
      - jq
      - awscli
      - pass
    state: present

- name: make sure casks are installed
  community.general.homebrew_cask:
    name:
      - font-iosevka
      - alfred
      - deezer
    state: present
