- name: make sure syncthing is installed
  community.general.homebrew:
    name:
      - syncthing
    state: present

- name: make sure qsyncthingtray is installed
  community.general.homebrew_cask:
    name:
      - qsyncthingtray
    state: present

- name: Start Syncthing Service
  command: brew services start syncthing
