- name: install neovim on darwin
  community.general.homebrew:
    name: neovim
    state: present

- name: install neovim-python on darwin
  ansible.builtin.pip:
    name: neovim
    extra_args: --user
